# Generated by Django 4.2.3 on 2023-09-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Printed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(blank=True, choices=[('a5', 'A5'), ('a4', 'A4'), ('a3', 'A3'), ('a2', 'A2'), ('a1', 'A1'), ('a0', 'A0')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lang',
            field=models.CharField(blank=True, choices=[('krill', 'krill'), ('english', 'english'), ('russian', 'russian'), ('uzbek', 'uzbek')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('book', 'Book'), ('clothing', 'Clothing'), ('product', 'Product')], default='product', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='script',
            field=models.CharField(blank=True, choices=[('krill', 'krill'), ('english', 'english'), ('russian', 'russian'), ('uzbek', 'uzbek')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wrapper',
            field=models.CharField(blank=True, choices=[('qattiq', 'qattiq'), ('yumshoq', 'yumshoq')], max_length=25, null=True, verbose_name='Muqova'),
        ),
        migrations.AddField(
            model_name='product',
            name='year_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_author', to='product.author'),
        ),
        migrations.AddField(
            model_name='product',
            name='printed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_publish', to='product.printed'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='product_tags', to='product.tag'),
        ),
    ]
