# Generated by Django 3.2.18 on 2023-03-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230319_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.bannerdiscount'),
        ),
    ]
