# Generated by Django 4.2.3 on 2023-09-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_wrapper_productimage_wrapper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='format',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='product',
            name='printed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='script',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_pages',
        ),
        migrations.RemoveField(
            model_name='product',
            name='year_of_creation',
        ),
        migrations.DeleteModel(
            name='Printed',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
