# Generated by Django 3.2.18 on 2023-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_bannerdiscount_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_uz',
            field=models.TextField(null=True),
        ),
    ]
