# Generated by Django 4.2.3 on 2023-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_author_product_language_product_yozuv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerdiscount',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
