# Generated by Django 4.2.3 on 2023-09-27 14:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('HOT', 'HOT'), ('BEST SELL', 'BEST SELL'), ('SALE', 'SALE')], default='NEW', max_length=10, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('view', models.PositiveIntegerField(default=0)),
                ('availability', models.PositiveIntegerField()),
                ('has_size', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_advertisement', to='product.advertisement')),
                ('banner_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_banner_discount', to='product.bannerdiscount')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_brand', to='product.brand')),
                ('size', models.ManyToManyField(blank=True, related_name='clothing_sizes', to='product.size')),
                ('tags', models.ManyToManyField(blank=True, related_name='clothing_tags', to='clothing.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
