# Generated by Django 3.2.18 on 2023-03-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('order', '0002_auto_20230319_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_cart_items', to='base.variant'),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
